export const PROVINCES_VN: string[] = [
  "Hà Nội", "Hải Phòng", "Hồ Chí Minh", "Đà Nẵng", "Cần Thơ",
  "Bắc Giang", "Bắc Kạn", "Cao Bằng", "Điện Biên", "Hà Giang",
  "Hà Nam", "Hòa Bình", "Lai Châu", "Lạng Sơn", "Lào Cai",
  "Nam Định", "Ninh Bình", "Phú Thọ", "Quảng Ninh", "Sơn La",
  "Thái Bình", "Thái Nguyên", "Tuyên Quang", "Vĩnh Phúc", "Yên Bái",
  "Bắc Ninh", "Hải Dương", "Hưng Yên", "Thanh Hóa", "Nghệ An",
  "Hà Tĩnh", "Quảng Bình", "Quảng Trị", "Huế", "Quảng Nam",
  "Quảng Ngãi", "Bình Định", "Phú Yên", "Khánh Hòa", "Ninh Thuận",
  "Bình Thuận", "Gia Lai", "Đắk Lắk", "Đắk Nông", "Kon Tum",
  "Lâm Đồng", "Bình Dương", "Bình Phước", "Đồng Nai", "Tây Ninh",
  "Bà Rịa - Vũng Tàu", "Long An", "Tiền Giang", "Bến Tre", "Trà Vinh",
  "Vĩnh Long", "Đồng Tháp", "An Giang", "Kiên Giang", "Hậu Giang",
  "Sóc Trăng", "Bạc Liêu", "Cà Mau",
];

export const COMMUNE_MAP: Record<string, string[]> = {
  "Thái Nguyên": [
    "P. Đồng Quang (TP. Thái Nguyên)",
    "P. Gia Sàng (TP. Thái Nguyên)",
    "P. Hoàng Văn Thụ (TP. Thái Nguyên)",
    "P. Phan Đình Phùng (TP. Thái Nguyên)",
    "P. Quang Trung (TP. Thái Nguyên)",
    "P. Thịnh Đán (TP. Thái Nguyên)",
    "P. Trung Thành (TP. Thái Nguyên)",
    "P. Tân Lập (TP. Thái Nguyên)",
    "P. Tân Thịnh (TP. Thái Nguyên)",
    "P. Tân Cương (TP. Thái Nguyên)",
    "P. Túc Duyên (TP. Thái Nguyên)",
    "P. Quyết Thắng (TP. Thái Nguyên)",
    "Xã Phúc Hà (TP. Thái Nguyên)",
    "Xã Phúc Xuân (TP. Thái Nguyên)",
    "Xã Sơn Cẩm (TP. Thái Nguyên)",
    "Xã Cao Ngạn (TP. Thái Nguyên)",
    "Xã Huống Thượng (TP. Thái Nguyên)",
    "Xã Đồng Bẩm (TP. Thái Nguyên)",
    "Xã Thịnh Đức (TP. Thái Nguyên)",
    "Xã Tích Lương (TP. Thái Nguyên)",
    "Xã Quân Chu (H. Đại Từ)",
    "Xã Phú Xuyên (H. Đại Từ)",
    "Xã Bản Ngoại (H. Đại Từ)",
    "Xã Tiên Hội (H. Đại Từ)",
    "Xã Cù Vân (H. Đại Từ)",
    "Xã Ký Phú (H. Đại Từ)",
    "Xã Tân Thái (H. Đại Từ)",
    "Xã Vạn Thọ (H. Đại Từ)",
    "Xã Văn Yên (H. Đại Từ)",
    "Xã Yên Lãng (H. Đại Từ)",
    "Xã Phú Cường (H. Đại Từ)",
    "Xã Phú Lạc (H. Đại Từ)",
    "Xã Phú Thịnh (H. Đại Từ)",
    "Xã Đức Lương (H. Đại Từ)",
    "Xã La Bằng (H. Đại Từ)",
    "Xã Hoàng Nông (H. Đại Từ)",
    "Xã Khôi Kỳ (H. Đại Từ)",
    "Xã An Khánh (H. Đại Từ)",
    "Xã Mỹ Yên (H. Đại Từ)",
    "Xã Bình Thuận (H. Đại Từ)",
    "Xã Lục Ba (H. Đại Từ)",
    "Xã Phú Đình (H. Đại Từ)",
    "Xã Cát Nê (H. Đại Từ)",
    "TT. Đại Từ (H. Đại Từ)",
    "P. Bắc Sơn (TX. Phổ Yên)",
    "P. Ba Hàng (TX. Phổ Yên)",
    "P. Bãi Bông (TX. Phổ Yên)",
    "P. Đồng Tiến (TX. Phổ Yên)",
    "P. Phố Cò (TX. Phổ Yên)",
    "Xã Tân Phú (TX. Phổ Yên)",
    "Xã Minh Đức (TX. Phổ Yên)",
    "Xã Đắc Sơn (TX. Phổ Yên)",
    "Xã Hồng Tiến (TX. Phổ Yên)",
    "Xã Nam Tiến (TX. Phổ Yên)",
    "Xã Tiên Phong (TX. Phổ Yên)",
    "Xã Vạn Phái (TX. Phổ Yên)",
    "Xã Phúc Tân (TX. Phổ Yên)",
    "Xã Phúc Thuận (TX. Phổ Yên)",
    "Xã Trung Thành (TX. Phổ Yên)",
    "Xã Thành Công (TX. Phổ Yên)",
    "Xã Thuận Thành (TX. Phổ Yên)",
    "Xã Đông Cao (H. Phú Bình)",
    "Xã Dương Thành (H. Phú Bình)",
    "Xã Hà Châu (H. Phú Bình)",
    "Xã Kha Sơn (H. Phú Bình)",
    "Xã Lương Phú (H. Phú Bình)",
    "Xã Nhã Lộng (H. Phú Bình)",
    "Xã Tân Hòa (H. Phú Bình)",
    "Xã Tân Khánh (H. Phú Bình)",
    "Xã Thanh Ninh (H. Phú Bình)",
    "Xã Xuân Phương (H. Phú Bình)",
    "TT. Hương Sơn (H. Phú Bình)",
    "Xã Chùa Hang (H. Đồng Hỷ)",
    "Xã Minh Lập (H. Đồng Hỷ)",
    "Xã Nam Hòa (H. Đồng Hỷ)",
    "Xã Quang Sơn (H. Đồng Hỷ)",
    "Xã Tân Lợi (H. Đồng Hỷ)",
    "TT. Sông Cầu (H. Đồng Hỷ)",
    "Xã Cây Thị (H. Đồng Hỷ)",
    "Xã Văn Hán (H. Đồng Hỷ)",
    "Xã Hợp Tiến (H. Đồng Hỷ)",
    "TT. Đình Cả (H. Võ Nhai)",
    "Xã Bình Long (H. Võ Nhai)",
    "Xã Dân Tiến (H. Võ Nhai)",
    "Xã Nghinh Tường (H. Võ Nhai)",
    "Xã Phú Thượng (H. Võ Nhai)",
    "Xã Thần Sa (H. Võ Nhai)",
    "Xã Thượng Nung (H. Võ Nhai)",
    "Xã Vũ Chấn (H. Võ Nhai)",
    "TT. Chợ Chu (H. Định Hóa)",
    "Xã Bảo Linh (H. Định Hóa)",
    "Xã Bình Thành (H. Định Hóa)",
    "Xã Đồng Thịnh (H. Định Hóa)",
    "Xã Kim Phượng (H. Định Hóa)",
    "Xã Phú Đình (H. Định Hóa)",
    "Xã Quy Kỳ (H. Định Hóa)",
    "Xã Trung Hội (H. Định Hóa)",
    "Xã Kim Sơn (H. Định Hóa)",
    "Xã Bảo Cường (H. Định Hóa)",
  ],
  "Hà Nội": [
    "P. Hoàn Kiếm", "P. Hàng Bạc", "P. Hàng Bồ", "P. Hàng Buồm",
    "P. Cầu Giấy", "P. Dịch Vọng", "P. Mai Dịch", "P. Nghĩa Đô",
    "P. Đống Đa", "P. Ô Chợ Dừa", "P. Khâm Thiên", "P. Văn Miếu",
    "P. Ba Đình", "P. Cống Vị", "P. Điện Biên", "P. Giảng Võ",
    "P. Hai Bà Trưng", "P. Bạch Đằng", "P. Đồng Nhân", "P. Lê Đại Hành",
    "P. Long Biên", "P. Bồ Đề", "P. Đức Giang", "P. Giang Biên",
    "Q. Hoàng Mai", "P. Đại Kim", "P. Định Công", "P. Giáp Bát",
    "Q. Thanh Xuân", "P. Kim Giang", "P. Nhân Chính", "P. Thanh Xuân Trung",
    "H. Đông Anh", "H. Gia Lâm", "H. Sóc Sơn", "H. Thạch Thất",
    "H. Chương Mỹ", "H. Thanh Trì", "H. Thường Tín", "H. Ứng Hòa",
  ],
  "Hồ Chí Minh": [
    "P. Bến Nghé (Q.1)", "P. Bến Thành (Q.1)", "P. Cầu Kho (Q.1)",
    "P. Phú Nhuận", "P. Tân Bình", "P. Bình Thạnh", "P. Gò Vấp",
    "P. Thủ Đức", "P. Bình Dương", "P. Long Thạnh Mỹ",
    "H. Bình Chánh", "H. Hóc Môn", "H. Củ Chi", "H. Nhà Bè", "H. Cần Giờ",
  ],
  "Hải Phòng": [
    "Q. Hồng Bàng", "Q. Ngô Quyền", "Q. Lê Chân", "Q. Hải An",
    "Q. Kiến An", "Q. Đồ Sơn", "Q. Dương Kinh",
    "H. An Dương", "H. An Lão", "H. Kiến Thụy", "H. Tiên Lãng",
    "H. Vĩnh Bảo", "H. Thủy Nguyên", "H. Cát Hải",
  ],
  "Lào Cai": [
    "P. Lào Cai", "P. Phố Mới", "P. Cốc Lếu", "P. Kim Tân",
    "Xã Bắc Cường", "Xã Đồng Tuyển", "Xã Vạn Hòa",
    "H. Bảo Thắng", "H. Bảo Yên", "H. Bát Xát", "H. Mường Khương",
    "H. Sa Pa", "H. Si Ma Cai", "H. Văn Bàn",
  ],
  "Nghệ An": [
    "TP. Vinh", "TX. Thái Hòa", "TX. Cửa Lò", "TX. Hoàng Mai",
    "H. Anh Sơn", "H. Con Cuông", "H. Diễn Châu", "H. Đô Lương",
    "H. Hưng Nguyên", "H. Kỳ Sơn", "H. Nam Đàn", "H. Nghi Lộc",
    "H. Nghĩa Đàn", "H. Quế Phong", "H. Quỳ Châu", "H. Quỳ Hợp",
    "H. Quỳnh Lưu", "H. Tân Kỳ", "H. Thanh Chương", "H. Tương Dương",
    "H. Yên Thành",
  ],
  "Thanh Hóa": [
    "TP. Thanh Hóa", "TX. Bỉm Sơn", "TX. Sầm Sơn",
    "H. Bá Thước", "H. Cẩm Thủy", "H. Đông Sơn", "H. Hà Trung",
    "H. Hậu Lộc", "H. Hoằng Hóa", "H. Lang Chánh", "H. Mường Lát",
    "H. Nga Sơn", "H. Ngọc Lặc", "H. Như Thanh", "H. Như Xuân",
    "H. Nông Cống", "H. Quan Hóa", "H. Quan Sơn", "H. Quảng Xương",
    "H. Thạch Thành", "H. Thiệu Hóa", "H. Thọ Xuân", "H. Thường Xuân",
    "H. Tĩnh Gia", "H. Triệu Sơn", "H. Vĩnh Lộc", "H. Yên Định",
  ],
};
