// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/erp-screens/DoanhNghiep.tsx": () => import("../components/mockups/erp-screens/DoanhNghiep.tsx"),
  "./components/mockups/erp-screens/DoanhNghiepDetail.tsx": () => import("../components/mockups/erp-screens/DoanhNghiepDetail.tsx"),
  "./components/mockups/erp-screens/Login.tsx": () => import("../components/mockups/erp-screens/Login.tsx"),
  "./components/mockups/erp-screens/User.tsx": () => import("../components/mockups/erp-screens/User.tsx")
};
